### PR TITLE
Added the end date and changed the change date function

### PR DESCRIPTION
**Pull request by Scoombe**
You can now select the end date of the project

### CODE REVIEW

**Comment by Scoombe** [comment]
closes #75

**Comment by Gaya** [comment]
Awesome, thanks! I will try and add an idea I had with selecting end dates. I wanted it to be an optional thing as it is yet another column in the timesheet. I am still thinking about the best way to go about this, but I'll try to figure it out this week.

**Comment by Scoombe** [comment]
Ok sounds good.

**Comment by Gaya** [comment]
I've been thinking about this a lot and think it's best if you make entering an end date an option. This will also make room to add more timesheet options in the settings.

I will build from what you've done here.

**Pull request merged**
