### PR TITLE
update mobile layout reports page

### PR DESCRIPTION
**Pull request by ThomasRoest**
small updates for mobile layout reports page (making the grid stackable and reorder on mobile)

### CODE REVIEW

**Comment by Gaya** [comment]
Will check it out tomorrow. Thank you for the help!

**Comment by ThomasRoest** [comment]
updated the save report form as well
form

**Comment by Gaya** [comment]
Thanks! Did you close this PR by accident perhaps?

**Comment by ThomasRoest** [comment]
yes sorry!

**Comment by Gaya** [comment]
Thank you for these updates. I'll add some work to it and merge.

**Pull request merged**
